### PR TITLE
feat: Add new navigation

### PR DESCRIPTION
**Pull request by Patrick1904**
This PR replaces the current navigation with a new navigation. Figma design found [here](https://www.figma.com/file/GS9OJozTJ1PZBkTfJ3V8g5/NearSocial-v1?node-id=0%3A1&t=kr3n5WzRXCVDuiZW-0).

**Logged out mobile**
Screen Shot 2023-01-12 at 4 28 17 PM

**Logged in mobile**
Screen Shot 2023-01-12 at 4 29 52 PM

**Logged out desktop**
Screen Shot 2023-01-12 at 4 29 12 PM

**Logged in desktop**
Screen Shot 2023-01-12 at 4 31 19 PM

### CODE REVIEW

**Comment by evgenykuzyakov** [comment]
Overall, this design is more fit for developers audience (assuming I understand Create button). Is it intended to be displayed on the different domain or by default for near.social?

- It's missing storage balance withdrawal option in the dropdown
- Create button has unclear purpose (maybe I miss the context, but does it show "fork"/"new" selection?).
- Profile can be a single widget, don't need to split it into the name and image separately. See https://near.social/#/mob.near/widget/WidgetSource?src=mob.near/widget/Profile.ShortInlineBlock
- Documentation and Editor are not needed for general audience, so should we enable them only for dev mode or separate domain?

**Comment by Patrick1904** [comment]
> Overall, this design is more fit for developers audience (assuming I understand Create button). Is it intended to be displayed on the different domain or by default for near.social?
> 
> * It's missing storage balance withdrawal option in the dropdown
> * Create button has unclear purpose (maybe I miss the context, but does it show "fork"/"new" selection?).
> * Profile can be a single widget, don't need to split it into the name and image separately. See https://near.social/#/mob.near/widget/WidgetSource?src=mob.near/widget/Profile.ShortInlineBlock
> * Documentation and Editor are not needed for general audience, so should we enable them only for dev mode or separate domain?

Thanks @evgenykuzyakov. Since we're considering UX/UI - should we find a suitable placement for view source and fork? Seems that may also be better viewed in a 'dev' mode, etc.

Screen Shot 2022-12-22 at 11 21 57 AM

cc @heycorwin

**Comment by evgenykuzyakov** [comment]
1) We should decrease top margin, since "View source" and "Fork" are under the hamburger now.

2) Hide "Profile" link from the mobile menu when not signed in.

**Comment by Patrick1904** [comment]
> 1. We should decrease top margin, since "View source" and "Fork" are under the hamburger now.

I suggest we keep some white space but I decreased it from 120px to 100px.

> 2. Hide "Profile" link from the mobile menu when not signed in.

I think it's preferable to let guest users know there is a profile, and where the button is located, but encourage the user to 'finish your profile by signing up' when they land on the empty profile page. WDYT?

**Comment by evgenykuzyakov** [comment]
> I think it's preferable to let guest users know there is a profile, and where the button is located, but encourage the user to 'finish your profile by signing up' when they land on the empty profile page. WDYT?

Let's disable this button, so it can't be clicked until you sign in.

**Comment by Patrick1904** [comment]
> > I think it's preferable to let guest users know there is a profile, and where the button is located, but encourage the user to 'finish your profile by signing up' when they land on the empty profile page. WDYT?
> 
> Let's disable this button, so it can't be clicked until you sign in.

Disabled the 'profile' button when logged out:

Screen Shot 2023-01-12 at 5 20 16 PM

**Review by evgenykuzyakov — APPROVED** [review]

**Pull request merged**
