### PR TITLE
Secure iframe

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
This change add `iframe` to the list of approved tags that can be used by VM.

The iframe takes the following properties: `className, style, src, srcDoc, title, message, onMessage`. The iframe has a sandbox property set to `sandbox="allow-scripts"`, which only allows scripts.

`message` and `onMessage` are used to communicate with this iframe instance.

- `message` will be passed to the iframe every time, the deep equal is different or the iframe is recreated. The message is passed using `contentWindow.postMessage(message, "*")` on the iframe.
- `onMessage(data)` is called when the iframe passes a message to `window.top`. Only `event.data` is passed to the `onMessage`

Iframes can be used to embed external HTML or to use custom DOM elements, for example `canvas`. 

The following example demonstrates how you can use an iframe to call `eval`:
```jsx
State.init({
  text: `"b" + "a" + +"a" + "a"`,
});

const code = `
<div>Expression: <pre id="exp" /></div>
<div>Results: <pre id="res" /></div>

<script>
    window.top.postMessage("loaded", "*");
    window.addEventListener("message", (event) => {
        const data = event.data
        document.getElementById("exp").innerHTML = JSON.stringify(data);
        try {
            const result = eval(data.exp);
            document.getElementById("res").innerHTML = result;
            event.source.postMessage(result, "*");
        } catch (e) {
            // ignore
        }
    }, false);
</script>
`;

return (
  <div>
    <input
      value={state.text || ""}
      onChange={(e) => State.update({ text: e.target.value })}
    />
    Iframes below
    <div className="d-flex">
      <iframe
        className="w-50 border"
        srcDoc={code}
        message={{ exp: state.text || "" }}
        onMessage={(res1) => State.update({ res1 })}
      />
      <iframe
        className="w-50 border"
        srcDoc={code}
        message={{ exp: (state.text || "") + " + ' banana'" }}
        onMessage={(res2) => State.update({ res2 })}
      />
    </div>
    Result:{" "}
    <pre>
      res1 = {JSON.stringify(state.res1)}
      res2 = {JSON.stringify(state.res2)}
    </pre>
  </div>
);
```

Screen Shot 2023-02-01 at 11 13 44 AM

### CODE REVIEW

**Comment by mpeterdev** [comment]
@evgenykuzyakov I am happy to review this and raise any red flags, but I want to be clear in my skillset that my input should not be taken as a "security review" with approval indicating the absence of attack vectors

This seems like an addition where we might want to get eyes from the Pagoda security team or another reviewer they recommend

**Comment by mpeterdev** [comment]
Important focus for anyone else who reviews: is there any way to communicate code for execution via `postmessage` which might bypass the VM?

Currently the answer seems like no. The structured clone algorithm prevents functions from being passed, and passing a string would run up against the same limitations of trying to define a function as a string directly in component code

**Review by mpeterdev — APPROVED** [review]
I did not find any vulnerabilities in my testing

**Comment by evgenykuzyakov** [comment]
Another example uses external npm library to make an Markdown editor:
```jsx
const initialText = "# Hello World\n\n";
State.init({
  m: initialText,
});

const code = `
<script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
<script src="https://unpkg.com/react-markdown-editor-lite@1.3.4/lib/index.js" crossorigin></script>
<link rel="stylesheet" href="https://unpkg.com/react-markdown-editor-lite@1.3.4/lib/index.css" />


<div id="react-root"></div>

<script>
function TestReact(props) {
  const [value, setValue] = React.useState(props.initialText || "");
  return React.createElement(ReactMarkdownEditorLite.default, {
      value,
      view: { menu: true, md: true, html: false },
      canView: { menu: true, md: false, html: false, fullScreen: false, hideMenu: true },
      onChange: ({ text }) => {
        setValue(text);
        window.top.postMessage(text, "*");
      },
      renderHTML: () => {},
      className: "full",
    }); 
}

const domContainer = document.querySelector('#react-root');
const root = ReactDOM.createRoot(domContainer);

window.addEventListener("message", (event) => {
  root.render(React.createElement(TestReact, {
    initialText: event.data,
  }));
});

</script>
`;

return (
  <div>
    <iframe
      className="w-100"
      style={{ height: "300px" }}
      srcDoc={code}
      message={initialText}
      onMessage={(m) => State.update({ m })}
    />
    <Markdown text={state.m} />
  </div>
);
```

Screen Shot 2023-02-03 at 4 54 56 PM

**Pull request merged**
